kind: Deployment
apiVersion: apps/v1
metadata:
  name: oauthviewer
  labels:
    app: oauthviewer
    app.kubernetes.io/component: oauthviewer
    app.kubernetes.io/instance: oauthviewer
    app.kubernetes.io/name: oauthviewer
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: oauthviewer
  template:
    metadata:
      labels:
        deployment: oauthviewer
    spec:
      containers:
        - name: oauthviewer
          image: >-
            image-registry.openshift-image-registry.svc:5000/cp4i/oauthviewer:latest
          ports:
            - containerPort: 8000
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
          env:
            - name: HOSTNAME
              value: apps.daffy-51cmp7rx.cloud.techzone.ibm.com
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          resources:
            requests:
              memory: "500Mi"
              cpu: 1
            limits:
              memory: "2048Mi"
              cpu: 2
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 5 
            failureThreshold: 5 
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
