kind: Deployment
apiVersion: apps/v1
metadata:
  name: apiloadgenerator
  labels:
    app: apiloadgenerator
    app.kubernetes.io/component: apiloadgenerator
    app.kubernetes.io/instance: apiloadgenerator
    app.kubernetes.io/name: apiloadgenerator
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: apiloadgenerator
  template:
    metadata:
      labels:
        deployment: apiloadgenerator
    spec:
      containers:
        - name: apiloadgenerator
          image: >-
            image-registry.openshift-image-registry.svc:5000/cp4i/apiloadgenerator:latest
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          resources:
            requests:
              memory: "1024Mi"
              cpu: 1
            limits:
              memory: "1024Mi"
              cpu: 1
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
