kind: Deployment
apiVersion: apps/v1
metadata:
  name: aggregator
  labels:
    app: aggregator
    app.kubernetes.io/component: aggregator
    app.kubernetes.io/instance: aggregator
    app.kubernetes.io/name: aggregator
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: aggregator
  template:
    metadata:
      labels:
        deployment: aggregator
    spec:
      containers:
        - name: aggregator
          image: >-
            image-registry.openshift-image-registry.svc:5000/cp4i/aggregator:latest
          ports:
            - containerPort: 8000
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
          env:
            - name: HOSTNAME
              value: apps.daffy-6bom7bh1.cloud.techzone.ibm.com
            - name: CLIENT_ID
              value: edd5843d14fd23e9519d2d59d35eb65a
            - name: CLIENT_SECRET
              value: a0b4fdc11343c00c407e8b6caadd3987
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          resources:
            requests:
              memory: "500Mi"
              cpu: 1
            limits:
              memory: "2048Mi"
              cpu: 2
          livenessProbe:
            tcpSocket:
              port: 8443
            initialDelaySeconds: 60
            periodSeconds: 5 
            failureThreshold: 5 
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
